#!/usr/bin/env python3
"""Generate MCP tools from the frozen daemon contract or a daemon Unix socket.

Default: python3 scripts/gen-tools-static.py [--check]
Live:    python3 scripts/gen-tools-static.py --socket /path/to/chitta.sock

Existing MCP schema adaptations are intentional compatibility constraints. This
script does not import the MCP SDK, start a daemon, or read the generated output
as input. Review contracts/mcp-tools.json whenever the daemon contract changes.
"""

from __future__ import annotations

import argparse
import ast
import copy
import json
import pprint
import runpy
import socket
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MCP = ROOT / "chitta-mcp"


def composite_handlers(server_path: Path) -> set[str]:
    """Read the explicit registry without executing server startup code."""
    tree = ast.parse(server_path.read_text())
    for node in tree.body:
        if isinstance(node, ast.Assign) and any(
            isinstance(target, ast.Name) and target.id == "COMPOSITE_HANDLERS"
            for target in node.targets
        ):
            return {ast.literal_eval(key) for key in node.value.keys}
    raise ValueError("server.py has no COMPOSITE_HANDLERS registry")


def fetch_tools(socket_path: str) -> list[dict]:
    """Issue only tools/list; require a complete successful response."""
    with socket.socket(socket.AF_UNIX, socket.SOCK_STREAM) as sock:
        sock.settimeout(30)
        sock.connect(socket_path)
        sock.sendall(b'{"jsonrpc":"2.0","id":1,"method":"tools/list","params":{}}\n')
        with sock.makefile("rb") as stream:
            response = json.loads(stream.readline())
    return response["result"]["tools"]


def legacy_schema(obj):
    """Preserve the established MCP integer/null/bounds/description conventions."""
    if isinstance(obj, dict):
        result = {
            key: legacy_schema(value)
            for key, value in obj.items()
            if value is not None and key not in {"minimum", "maximum", "maxItems"}
        }
        if result.get("type") == "integer":
            del result["type"]
            result["anyOf"] = [{"type": "integer"}, {"type": "string"}]
        return result
    if isinstance(obj, list):
        return [legacy_schema(item) for item in obj]
    if isinstance(obj, str):
        # The original sync script replaced these inside descriptions too.
        return obj.replace(": true", ": True").replace(": false", ": False")
    return obj


def daemon_row(tool: dict, descriptions: dict) -> dict:
    schema = legacy_schema(tool["inputSchema"])
    props = schema.setdefault("properties", {})
    # Published MCP parameters predate these daemon-only additions. Preserve
    # the API during this extraction; migration requires a separate contract PR.
    omitted = {
        "recall": ("pool", "prefilter", "strategy"),
        "recall_keyword": ("realm",),
        "symbol_callees": ("path",),
        "session_list": ("active_only", "ttl_seconds"),
    }
    for key in omitted.get(tool["name"], ()):
        props.pop(key, None)
    if tool["name"] == "find_symbol":
        props.update(lang={"type": "string"}, path={"type": "string"}, limit={"type": "integer"})
    return {
        "name": tool["name"],
        "description": descriptions.get(tool["name"], tool["description"]),
        "inputSchema": schema,
    }


def generate(tools: list[dict]) -> str:
    if not tools or len({tool["name"] for tool in tools}) != len(tools):
        raise ValueError("daemon tools must be nonempty with unique names")
    composites = runpy.run_path(str(MCP / "tools_composite.py"))["COMPOSITE"]
    compat = runpy.run_path(str(MCP / "tools_compat.py"))
    overrides = compat["DAEMON_OVERRIDES"]
    missing = {tool["name"] for tool in composites} - composite_handlers(MCP / "server.py")
    if missing:
        raise ValueError(f"composites without handlers: {', '.join(sorted(missing))}")
    unknown = {tool["name"] for tool in overrides} - {tool["name"] for tool in tools}
    if unknown:
        raise ValueError(f"schema overrides without daemon tools: {', '.join(sorted(unknown))}")
    local = copy.deepcopy(composites + overrides)
    if len({tool["name"] for tool in local}) != len(local):
        raise ValueError("duplicate composite/override names")
    header = '''#!/usr/bin/env python3
"""Generated by scripts/gen-tools-static.py; DO NOT EDIT.

Sources: contracts/daemon-tools.json, tools_composite.py, tools_compat.py.
Regenerate: python3 scripts/gen-tools-static.py
Verify:     python3 scripts/gen-tools-static.py --check
"""

from mcp.types import Tool
'''
    for name, rows in (
        ("TOOLS", [daemon_row(tool, compat["DESCRIPTION_OVERRIDES"]) for tool in tools]),
        ("COMPOSITE_TOOLS", local),
    ):
        # Stable names, keys and literals; no timestamps, environment or formatter dependency.
        header += f"\n{name} = [Tool(**row) for row in "
        header += pprint.pformat(
            sorted(rows, key=lambda row: row["name"]), width=100, sort_dicts=True
        )
        header += "]\n"
    return header


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    source = parser.add_mutually_exclusive_group()
    source.add_argument("--daemon-tools", type=Path, default=ROOT / "contracts/daemon-tools.json")
    source.add_argument(
        "--socket", help="read tools/list from this Unix socket (no daemon startup)"
    )
    parser.add_argument("--output", type=Path, default=MCP / "tools_static.py")
    parser.add_argument("--check", action="store_true", help="fail if output is missing or stale")
    args = parser.parse_args()
    tools = fetch_tools(args.socket) if args.socket else json.loads(args.daemon_tools.read_text())
    content = generate(tools)
    if args.check:
        if not args.output.exists() or args.output.read_text() != content:
            print(f"stale: {args.output}; run python3 scripts/gen-tools-static.py")
            return 1
        print("static tools unchanged")
    else:
        args.output.write_text(content)
        print(f"generated {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
